File Upload
Emaro/Liberica pull request #30
Opened 2017-05-01 17:09 UTC by david-schor

Added file upload function

2017-05-01 19:39 UTC, Emaro requested changes
Top. Only the validation of the pictures is not really clear

2017-05-01 19:39 UTC, Emaro commented on mvc/Controller/commands.php
> +        if(!in_array($_POST['picture'], $allowed_extensions))
$_POST['picture'] or just the extention needed?

2017-05-01 20:30 UTC, david-schor commented on mvc/Controller/commands.php
> +        if(!in_array($_POST['picture'], $allowed_extensions))
Im not sure but i think only the extention is needed.
I would recommend this:
`$ext = end((explode(".", $_POST['picture'])));
if(in_array($ext, $allowed_extension)){} `

By the way i found an mistake made by me: there shouldn't be a **!** in the if.
I will fix and finish it!

2017-05-02 18:37 UTC, Emaro approved these changes

2017-05-02 18:37 UTC, merged